### ISSUE TITLE
Change the popup of turn on location

### ISSUE THREAD

**Issue by tharasafoodadda** [codewithshinde/lw-foodapp-types#14]

**Comment by tharasafoodadda** [comment]
Please change the popup for asking to turn on the location,it is showing the wrong popup whaen we tap on it it is taking to permission not taking to location on and off page 
![Uploading Screenshot_2024-04-04-19-59-46-38_3f4d9f0ce490ef06a9401128999a0ea4.jpg…]()

**Comment by tharasafoodadda** [comment]
Please change the popup for asking to turn on the location,it is showing the wrong popup whaen we tap on it it is taking to permission not taking to location on and off page

**Comment by codewithshinde** [comment]
This is fixed in version 1.7.0
