### ISSUE TITLE
Need to update customer view when order has been cancelled

### ISSUE THREAD

**Issue by tharasafoodadda** [codewithshinde/lw-foodapp-types#16]

**Comment by tharasafoodadda** [comment]
Need to update customer home page when order has been rejected by the restaurant it is stil showing ttrack order,it should update that  it is cancelled instead of track order
![Screenshot_2024-04-10-19-05-47-43_7352322957d4404136654ef4adb64504](https://github.com/codewithshinde/lw-foodapp-types/assets/154573368/affbf853-1bd3-40df-9d61-5a27e2ed0181)
![Screenshot_2024-04-10-19-05-43-80_7352322957d4404136654ef4adb64504](https://github.com/codewithshinde/lw-foodapp-types/assets/154573368/8e471322-d68b-4208-9a30-5666a1327aec)

**Comment by codewithshinde** [comment]
Fixed !
