### ISSUE TITLE
Showing error od deler the dish insterd of validate the restaurant

### ISSUE THREAD

**Issue by tharasafoodadda** [codewithshinde/lw-foodapp-types#17]

**Comment by tharasafoodadda** [comment]
When the new restaurant is added,raised for review ,in admin pannel it is showing are u sure y want to delete dish unsted of accept 
![IMG20240423064748](https://github.com/codewithshinde/lw-foodapp-types/assets/154573368/52018a3c-7fdb-4278-ab7c-fa957fa6cdbd)

**Comment by codewithshinde** [comment]
Fixed
